name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    -
      cron: '0 0 * * *' # Runs every day, on the day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://tech-andgar.me/index.xml"
          user_agent: "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.113 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
          item_exec: "if (!post.title) post = null;" #to skip post that dont have title

